CREATE DATABASE IF NOT EXIST db_todolist;

USE db_todolist;

CREATE TABLE IF NOT EXISTS task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR?(255) NOT NULL,
  completed BOOLEAN DEFAULT false
);